name: ci

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.6
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.6
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew.bat build
      - uses: actions/upload-artifact@v3
        with:
          name: JavaFinder Windows
          path: |
            build/libs


  build-mac:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.6
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.6
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: JavaFinder Mac
          path: |
            build/libs


  build-linux:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.6
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.6
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: JavaFinder Linux
          path: |
            build/libs