name: BuildNativeImage
on: [push, pull_request]
jobs:
  build-macos:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.6
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.6
          distribution: zulu
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build --scan
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'

      - name: Build native-image on Macos
        run: native-image -cp classes:./build/libs/javafinder-17.0.3-fat.jar --initialize-at-build-time=Constants -H:Name=javafinder eu.hansolo.javafinder.Main --no-fallback

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: javafinder-mac-x64
          path: javafinder*


  build-linux:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.6
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.6
          distribution: zulu
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build --scan
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'

      - name: Build native-image on Linux
        run: native-image -cp classes:./build/libs/javafinder-17.0.3-fat.jar --initialize-at-build-time=Constants -H:Name=javafinder eu.hansolo.javafinder.Main --no-fallback

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: javafinder-linux-x64
          path: javafinder*


  build-windows:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.6
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.6
          distribution: zulu
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build --scan
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'

      - name: Build native-image on Windows
        run: native-image.cmd -jar ".\build\libs\javafinder-17.0.3-fat.jar" --initialize-at-build-time=Constants --no-server -H:Name=javafinder --no-fallback --static
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: javafinder-windows-x64
          path: javafinder*
